### ISSUE TITLE
Arrays of length 1 are collapsed into objects

### ISSUE THREAD

**Issue by psexton** [fangq/jsonlab#1]
A json file with contents:

```
{
    "maintainers": [
        {
            "name": "Paul Sexton",
            "email": "psexton@gnresound.com"
        }
    ]
}
```

if passed through `loadjson` and `savejson`, will turn into a json file with contents:

```
{
        "maintainers": {
            "name": "Paul Sexton",
            "email": "psexton@gnresound.com"
        }
}
```

**Comment by fangq** [comment]
@psexton 

FYI, I made one update today and now you can set 'NoRowBracket' to 0 to force adding a bracket. see this thread:

https://groups.google.com/d/msg/iso2mesh-users/u_CJT-TFu_8/oI3PXwyJvS4J

**Comment by fangq** [comment]
Duplicate to Issue #8.
