### ISSUE TITLE
Bug in processing backslash

### ISSUE THREAD

**Issue by stephenHartzell** [fangq/jsonlab#2]
I believe that line 284 in savejson.m should be removed. A backslash in a string does not need to be replaced with two backslashes because sprintf is used with the format argument: %s on line 297 copied below.

txt=sprintf('%s%s',txt,sep);

Furthermore, replacing one backslash with two backslashes precludes creating unicode strings such as 'm/s\u00b2' with the jsonlab library.

**Comment by fangq** [comment]
@stephenHartzell 

thanks for your feedback. I just made the following commit to address this issue, 

https://github.com/fangq/jsonlab/commit/dc4f0e71e6840abb7fb94d1955b8e79632b45319

please test it and let me know if this 1) has fixed the problem you mentioned and 2) has any additional issues.

**Comment by stephenHartzell** [comment]
fangq, as far as I can tell the issue is still present. (Sorry it took so long to reply, I've been very busy.) The reason why this has come up for me, is that I'm trying to output unicode values. For example, the following code

json_data.unicode = 'm/s\u00b2';
str = savejson('json_data',json_data)

yeilds

{
	"json_data": {
		"unicode": "m\/s\\u00b2"
	}
}

whereas the desired output is

{
	"json_data": {
		"unicode": "m/s\u00b2"
	}
}

**Comment by fangq** [comment]
@stephenHartzell 

thanks for following up with this issue.

I agree with you that adding an additional "\" before \uXXXX has problems. But for the slash before "s", I believe it should be escaped based on JSON's spec.

here I made the following change to remove the double back-slashes before the unicode.

https://github.com/fangq/jsonlab/commit/70a8ed195e2769b34bff7a4cc936db2ddedead1e

I am reopening the bug, let me know if this is what you have hoped. if so, feel free to close the bug.

**Comment by stephenHartzell** [comment]
You are correct about the slash before the "s". I just forgot to put it there in my "expected output". 

Your fix seems to work. Thanks so much! That's fantastic.
