### ISSUE TITLE
st not exist, and can you add a filter to ignore huge arrays?

### ISSUE THREAD

**Issue by dawnsong** [fangq/jsonlab#21]
```
  434 function txt=matlabobject2json(name,item,level,varargin)
+ 435 st = struct();
  436 if numel(item) == 0 %empty object
```

In the "+" initialization, it will not complain about "st" not found.

And can you add an option to ignore huge arrays? Since it is not efficient/meaningful to save huge 3D/4D arrays into text file and load back. 
Thanks for the useful json tool.

**Comment by fangq** [comment]
I could not reproduce the "st not found" complains. what version of matlab are you using?

**Comment by dawnsong** [comment]
I am using 2012b, and tried to save GIFT's (an ICA software) parameters.

Thanks for your work on jsonlab, very helpful:)

**Comment by fangq** [comment]
for large 3D/4D data, it is not uncommon to package such data with JSON. loading/saving efficiency do get a hit when the data complex increases (such as nested and large number of leaves) but for a simple large 3D/4D array, loading/saving is actually pretty fast.

if you do need efficiency, use saveubjson/loadubjson pair, these two functions can pack binary data and are significantly faster than savejson/loadjson for large data files.
