### ISSUE TITLE
structure arrays imported as cell arrays

### ISSUE THREAD

**Issue by ntholling** [fangq/jsonlab#22]
In demo_jsonlab_basic.m, lines 133-141, the demo creates a 3 element structure array, exports it to json, and then imports it back to a MATLAB variable (json2data).  However, it does not work as intended.  json2data is a cell array with three structures instead of a three-element structure array.  It is easily transformed by: 
`json2data = cell2mat(json2data);`
_assuming _ the structures all have the same fields.  Unfortunately, I do not have the time to chase down the root cause of the issue, but I thought you should know.  
Thanks for a very handy utility!
-Nathaniel

**Comment by fangq** [comment]
This is not a bug. The results are expected because savejson added a root to the struct. If you want generate a 3-element struct array, you should use the following code instead:

```
data2json=struct('name','Nexus Prime','rank',9);
data2json(2)=struct('name','Sentinel Prime','rank',9);
data2json(3)=struct('name','Optimus Prime','rank',9);
savejson('',data2json)
json2data=loadjson(ans,'SimplifyCell',1)
```

Feel free to reopen this issue if you find additional problems.

**Comment by ntholling** [comment]
Thank you, your comment answered the issue I raised.  This is an excellent utility, and I appreciate your prompt attention.

-Nathaniel
