### ISSUE TITLE
Float issue with py-ubjson file

### ISSUE THREAD

**Issue by rconan** [fangq/jsonlab#25]
Hi,
I am trying to import in Matlab a ubj file generated with py-ubjson.
Everything works fine, except for float?
Any idea why?
in python:
import ubjson
d = {'string': 'test', 'int': 123456,'pi':3.1415}
ubjson.dump(d,open('test.ubj','w'))
in Matlab:
s = loadubjson('test.ubj'')
s = 
       int: 123456
        pi: 1.0965e+227
    string: [116 101 115 116]

**Comment by fangq** [comment]
I looked into this, it looks like py-ubjson saved the floating point (double in this case) in the Big-endian format, even the host machine is a little-endian machine.

The UBJSON specs Draft-12 is not exactly clear on the byte orders for floats.
