### ISSUE TITLE
Error with table data

### ISSUE THREAD

**Issue by pjkoprowski** [fangq/jsonlab#29]
@fangq 

An indexing error occurs when parsing table data using savejson.m

For instance, if one calls the following:

`>> j = savejson('test_data', open('census1994.mat'), 'test.json');`

you get the following error:

> Error using savejson>matlabobject2json (line 444)
> You cannot subscript a table using only one subscript. Table subscripting requires both row and variable subscripts.
> 
> Error in savejson>obj2json (line 175)
>     txt=matlabobject2json(name,item,level,varargin{:});
> 
> Error in savejson>struct2json (line 285)
>       txt{end+1}=obj2json(names{e},item(i,j).(names{e}),...
> 
> Error in savejson>obj2json (line 171)
>     txt=struct2json(name,item,level,varargin{:});
> 
> Error in savejson (line 140)
> json=obj2json(rootname,obj,rootlevel,opt);

I hacked a solution, but I'm not sure if this leads to more issues with other files. See attached.

Cheers,

Paul
[paul_savejson.txt](https://github.com/fangq/jsonlab/files/506674/paul_savejson.txt)

**Comment by hillsm** [comment]
@paul

Your solution works in R2015b, but not in later versions. Moreover, table properties (like RowNames) are not preserved.

Greetings,

Michel

**Comment by fangq** [comment]
sorry @pjkoprowski and @hillsm for the long delay in processing this issue. I patched savejson with Paul's patch, and I also added support for RowNames, but in the current code, either the VariableNames or RowNames allows to have space or other non-variable-name strings. 

In the future, need to move valid_field() from loadjson to a separate unit and use it to convert Table name fields.
