### ISSUE TITLE
Error parsing array

### ISSUE THREAD

**Issue by toloko** [fangq/jsonlab#31]
In a JSON file, when using array notation (without quotes), only the first value is parsed. When trying to parse:

{   "value" : [3:10]  }

value will evaluate to 3. This problem is related to 'sscanf' function in line 179 from loadjson.m:
        	[obj, count, errmsg, nextidx]=sscanf(astr,'%f,',[1,inf]);

**Comment by fangq** [comment]
@toloko, "[3:10]" is not a valid JSON syntax, you can test it on http://jsonlint.com/
according to http://json.org, JSON array only supports comma-separated values.

**Comment by toloko** [comment]
Thanks for the comment and for your work.

Should it not 'loadjson' throw an error in such a case?

Thanks

**Comment by fangq** [comment]
interesting, the same line now evaluates as the anticipated result in matlab 2017a, but jsonlab should have thrown an error.

```
>> dd=loadjson('{ "value" : [3:10] }')

dd = 

  struct with fields:

    value: {[3 4 5 6 7 8 9 10]}
```
