### ISSUE TITLE
2D Matrix JSON representation

### ISSUE THREAD

**Issue by Andy1978** [fangq/jsonlab#42]
This is a question, not a bug report. And thanks for the wonderful library.

I wonder why a Matrix [1 2; 3 4] is saved as "[[1,2],[3,4]]" (columns as first dimension) and not as "[[1,3],[2,4]]" as a Matlab(and Fortran) user would expect. Is there some agreement under JSON users, how a Matrix is stored?

**Comment by fangq** [comment]
sorry for the late reply. JSON was derived from javascript. In javascript, 2D arrays were in row-major. On the other hand, the visual shape of the matrix in JSON text format matches the dimensions of the array, so I think it is more intuitive to interpret this way.

**Comment by philchiu-envision** [comment]
This I know this is an old issue, but it is worth nothing that this convention is opposite to that used by Matlab's own `jsonencode`/`jsondecode` and `mps.json.encode`/`mps.json.decode`.

**Comment by fangq** [comment]
@philchiu-envision, the convention difference between jsonlab and jsonencode/decode is not limited to array orders, but many other aspects, such as nan/inf representation, the use of _Array*_ keywords to convert high-D arrays, etc. So, jsonlab will unlikely to pursue a path to be compliant with MATLAB. On the other hand, in my opinion, it is still more intuitive for jsonlab to output arrays that matches the visual orientation of the array.

so, thanks for noting this, but we will unlikely to make any change. In the future, however, a special flag can be added to handle such case. Patch is welcome.
