### ISSUE TITLE
Garbage if key starts with underscore "_"

### ISSUE THREAD

**Issue by Andy1978** [fangq/jsonlab#43]
If you parse `loadjson ('{"a":5, "_id":6}')`

in GNU Octave you get:

    ans =
      scalar structure containing the fields:
        a =  5
        x0x5F_id =  6

see the added "x0x5F"

latest git 474d8c824800b5f2109c08f989085cb961acdbe3

**Comment by balancedtiger** [comment]
This is because `ans._id` is not a valid matlab field name.

A valid field name is created by first prepending `x0x` and then providing the hexadecimal representation of i.e. 
```
dec2hex('_') = 5F
```

**Comment by fangq** [comment]
@Andy1978, the answer provided by @balancedtiger is correct. special characters have to be converted first to use in MATLAB.

**Comment by Andy1978** [comment]
Okay, so this looks like a MATLAB only workaround(?) because `ans._id` works in GNU Octave without problem.

**Comment by fangq** [comment]
this is not a workaround, matlab variable naming rules have been there since 80's.

https://www.mathworks.com/help/matlab/matlab_prog/variable-names.html
https://www.mathworks.com/help/matlab/ref/isvarname.html
https://www.mathworks.com/help/matlab/ref/genvarname.html
