### ISSUE TITLE
jsonlab_selftest.m does not work in R2017a

### ISSUE THREAD

**Issue by hillsm** [fangq/jsonlab#44]
The script fails on the second example.

**Comment by rotton** [comment]
Same here, on 2017b (Win 10 Pro).
`Undefined function or variable 'st'.`

`Error in savejson>matlabobject2json (line 448)`
`txt=struct2json(name,st,level,varargin{:});`

**Comment by fangq** [comment]
@rotton, this issue was previously reported as Issue #39 and #34, and was fixed by this commit: https://github.com/fangq/jsonlab/commit/86ef12a57bbe54a8532c0e0015f52c7850519833 

can you download the latest version from github and test it again?
