### ISSUE TITLE
Bug in reading cell arrays

### ISSUE THREAD

**Issue by manyaafonso** [fangq/jsonlab#48]
I am trying to use jsonlab to process in Matlab object annotations in COCO format http://cocodataset.org/#format-data.

I am attaching a sample json file containing two annotations which should produce a cell-array under the tag segmentation. The issue is that 
data = loadjson( 'debug.JSON' ); 
reads the first one correctly as a cell array, but the second one is read as a matrix, which is totally not what we want!

[debug.JSON.txt](https://github.com/fangq/jsonlab/files/2265932/debug.JSON.txt)

Can you please fix this?

Thanks

**Comment by fangq** [comment]
thanks for reporting this. I could reproduce the issue, and I agree that mixing elements from different arrays is undesired, and should be fixed.

as a workaround, please add 'FastArrayParser', 0 in the parameter. the data will be parsed element-by-element, however, you can also see the simple arrays (such as the bbox field) are also parsed as cells.

```
>> data = loadjson( 'debug.JSON','FastArrayParser',0)

data = 

    [1x1 struct]    [1x1 struct]

>> data{2}

ans = 

              id: 67
        image_id: 3
     category_id: 2
    segmentation: {{1x12 cell}  {1x8 cell}  {1x20 cell}  {1x8 cell}  {1x12 cell}}
            area: 412064
            bbox: {[167]  [360]  [326]  [1264]}
         iscrowd: 0

>> data{1}

ans = 

              id: 28
        image_id: 0
     category_id: 2
    segmentation: {{1x40 cell}  {1x38 cell}  {1x8 cell}  {1x8 cell}  {1x20 cell}  {1x12 cell}  {1x26 cell}}
            area: 1609640
            bbox: {[0]  [0]  [1.0055e+03]  [1.6009e+03]}
         iscrowd: 0

>> 
```

**Comment by fangq** [comment]
you can also try this:
the output will be converted to a struct array.

```
>> data = loadjson( 'debug.JSON.txt','FastArrayParser',0, 'SimplifyCell',1)

data = 

1x2 struct array with fields:

    id
    image_id
    category_id
    segmentation
    area
    bbox
    iscrowd
>> data(1)

ans = 

              id: 28
        image_id: 0
     category_id: 2
    segmentation: {1x7 cell}
            area: 1609640
            bbox: [0 0 1.0055e+03 1.6009e+03]
         iscrowd: 0

>> data(2)

ans = 

              id: 67
        image_id: 3
     category_id: 2
    segmentation: {1x5 cell}
            area: 412064
            bbox: [167 360 326 1264]
         iscrowd: 0

>> 
```

**Comment by manyaafonso** [comment]
Hi @fangq , Thanks a lot for the help!
