### ISSUE TITLE
Suggested update - function handles

### ISSUE THREAD

**Issue by will-hill** [fangq/jsonlab#51]
Hi Fang,
I find this project useful for a current project.  Below is a change I made that you might find helpful.  I needed to serialize/deserialize function handles in Octave.  I do not know if it will work with Matlab.
  
182c182,185
< else
\---
\> elseif(is_function_handle(item))
\>     function_handle_struct = functions(item);
\>     txt=struct2json(name,function_handle_struct,level,varargin{:});
\> elseif(ismatrix(item))
183a187,188
\> else
\>     error('what is this object type?');

**Comment by fangq** [comment]
thanks @will-hill, I'd love to accept this update, but would prefer the change to be compatible with both matlab and octave. can you use this test as an example to refine your patch?

https://github.com/fangq/jsonlab/blob/master/savejson.m#L177

once it works with both, would be nice to send me a pull request (I am happy to manually patch if you have trouble doing so).

**Comment by fangq** [comment]
now saving function handle is supported. try

```
fun=@sin;
savejson('',fun)
```
