### ISSUE TITLE
savejson incorrectly stores matrix data

### ISSUE THREAD

**Issue by stephen-young** [fangq/jsonlab#54]
When loading a matrix from a json file with the loadjson function that was generated from the savejson function, it comes in as the transpose of the original rather than being identical to the original.

The following code:
```matlab
%% ArrayTest
bar = magic(4);
[~] = savejson('',bar,'bar.json');
test = loadjson('bar.json');
result = all(test == bar,'all')
result = all(test == bar','all')

%% ArrayInStructTest
foo.bar = magic(4);
[~] = savejson('',foo,'foo.json');
test = loadjson('foo.json');
result = all(test.bar == foo.bar,'all')
result = all(test.bar == foo.bar','all')
```
returns:

```matlab
result = 0
result = 1
result = 0
result = 1
```

**Comment by fangq** [comment]
sorry, the code is currently unstable due to the major restructure and changes, please try my above fix. the issue should have been fixed.

**Comment by stephen-young** [comment]
The fix worked. Thanks!

Going forward I'll keep jsonlab at tag v1.9.
