### ISSUE TITLE
How to preserve '/' in savejson without an additional '\'?

### ISSUE THREAD

**Issue by panovr** [fangq/jsonlab#56]
In MATLAB:
`data.file_name = 'images/001.jpg';`

with savejson:
`"file_name": "images\/001.jpg"`

We can see that savejson will output an additional '\\' in front of '/'.

May I ask how to preserve '/' in savejson without the additional '\\'?
Thanks!

**Comment by fangq** [comment]
see http://json.org/

'/' is one of the characters that need to be escaped by '\'
