### ISSUE TITLE
jdatadecode:str2func hides function from compiler

### ISSUE THREAD

**Issue by dwschmid** [fangq/jsonlab#59]
decompfun=str2func([zipmethod 'decode']);
in jdatadecode "hides" the called functions from the compiler. I.e. in deployed mode one ends up with e.g. missing zlibdecode, unless all of them are added manually to the project. 

BTW: Excellent package!

**Comment by dwschmid** [comment]
Well, you could have to write a series of IF statements (depending on the zipmethod) and then explicitly assign the function handle to decompfun, e.g. 
if strcmp( zipmethod, zlib)
   decompfun = @zlibdecode;
....
Not as compact as using str2func, but the compiler would then "see" what to include.

Ok if you want to close this. I just include the required files in the deploy project manually for now.

**Comment by fangq** [comment]
I expect more compression methods will be added in the future, so explicitly listing those will become a bit cumbersome. I am closing this issue for now, and will think about a more compact solution.

**Comment by dwschmid** [comment]
Other possibility would be to use the %#function pragma
