### ISSUE TITLE
Option to turn on and off the extended UBJSON N-D array syntax

### ISSUE THREAD

**Issue by fangq** [fangq/jsonlab#6]
While we will continue using these features by default in JSONLab, we need to implement an option to allow users to turn off such feature at their wishes.

such syntax was proposed here, and implemented as part of JSONLab 0.9

https://groups.google.com/d/msg/universal-binary-json/tgMCEbOmhes/s7JlCl58hvQJ

**Comment by bdyetton** [comment]
Hi fangq,
I'm converting between Matlab and Python using jsonLab. Thanks for the great toolbox. 
Was this feature to turn off the optimized ND array storage every implemented? 
I don't see it in the specs?
