### ISSUE TITLE
jsonlab toolbox

### ISSUE THREAD

**Issue by roslovets** [fangq/jsonlab#60]
Hi, are you interesting to create MATLAB toolbox from jsonlab? Because it's not very convenient to have jsonlab manually added to the MATLAB path. And it's not convenient at all to add jsonlab copy to every project where you use it.
I think that toolbox format is the best way to distribute, use and update jsonlab. Do you agree? And do you need help to create the toolbox?

**Comment by fangq** [comment]
I am absolutely interested - in the recent release, I added the package files for Octave (DESCRIPTION and INDEX). I haven't started looking into matlab packages - would you be willing to contribute?

**Comment by roslovets** [comment]
Great, I can create pull request
