### ISSUE TITLE
Booleans are saved as logical 0s and 1s

### ISSUE THREAD

**Issue by KiranPrakash** [fangq/jsonlab#62]
For a sample.json which has text: { "widget": false },  when I do loadjson('sample.json') the boolean is converted into logical 0 or 1 on matlab. Is there an argument that could be used for loadjson and savejson that could preserve the original boolean formats?
Thank you.

**Comment by fangq** [comment]
Please add `'ParseLogical',1` to the savejson call to preserve Boolean/logical, try
````
savejson('',loadjson('{ "widget": false }'),'ParseLogical',1)
```
