### ISSUE TITLE
problem with serialisation character arrays longer than 399 characters.

### ISSUE THREAD

**Issue by aardwolf-ge** [fangq/jsonlab#65]
Hello,
I have found a strange issue:
this code recreates it:
t= ''
for k=1:400
    t= [t 'x']
end
jt=savejson(t)

The character array is serialised as a double array.
Compare it to 399 in the loop where everything works fine.

**Comment by fangq** [comment]
hi @aardwolf-ge, this is now fixed.

if using jsonlab 2.0, a temporary workaround is to set `compressstringsize` to `inf`.
```
jt=savejson('t',t,'CompressStringSize',inf)
```

**Comment by aardwolf-ge** [comment]
That was extremely fast, but I have another one.
Wherever I use ‘FastArrayParser’ or ‘SimplifyCell’ or not it does not work for me.

Kind regards,

Jacek Szkutnik

Od: Qianqian Fang<mailto:notifications@github.com>
Wysłano: wtorek, 7 lipca 2020 15:31
Do: fangq/jsonlab<mailto:jsonlab@noreply.github.com>
DW: aardwolf-ge<mailto:jacek.szkutnik@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Temat: Re: [fangq/jsonlab] problem with serialisation character arrays longer than 399 characters. (#65)


hi @aardwolf-ge<https://github.com/aardwolf-ge>, this is now fixed.

if using jsonlab 2.0, a temporary workaround is to set compressstringsize to inf.

jt=savejson('t',t,'CompressStringSize',inf)

**Comment by fangq** [comment]
can you clarify your reply a little bit more? when you said "it does not work for me", were your referring to the `'compressstringsize',inf` command? or the patch I just committed?  or the two two additional options you  mentioned?

**Comment by aardwolf-ge** [comment]
Sorry, my bad.
The patch you have committed works perfectly.
When I was writing "it does not work for me" I meant the new issue I have opened a few minutes ago, the one about serialisation and de-serialisation of a one column table containing char data.
Sorry.

________________________________
Od: Qianqian Fang <notifications@github.com>
Wysłane: wtorek, 7 lipca 2020 16:36
Do: fangq/jsonlab <jsonlab@noreply.github.com>
DW: aardwolf-ge <jacek.szkutnik@hotmail.com>; Mention <mention@noreply.github.com>
Temat: Re: [fangq/jsonlab] problem with serialisation character arrays longer than 399 characters. (#65)


can you clarify your reply a little bit more? when you said "it does not work for me", were your referring to the 'compressstringsize',inf command? or the patch I just committed? or the two two additional options you mentioned?
