### ISSUE TITLE
One column table cannot be unserialised after serialisation

### ISSUE THREAD

**Issue by aardwolf-ge** [fangq/jsonlab#66]
This code recreates the problem
v=[ 1; 2 ]
tab= array2table(v)
str=savejson('',tab)
jv=loadjson(str)

producing the error 'The VariableNames property must contain one name for each variable in the table.'

the json object created by savejson is (in compact form)
`'{"_TableCols_":["v"],"_TableRows_":[],"_TableRecords_":[[1,2]]}'`

when changed to: 

`'{"_TableCols_":["v"],"_TableRows_":[],"_TableRecords_":[[1],[2]]}'`

it works properly, so the problem seems to be on the save side.

**Comment by aardwolf-ge** [comment]
this array: 
[ 1; 2 ]
is serialised to this json object:
'[[1],[2]]'
while this cell array:
{ 1; 2 }
is serialised to this json object:
'[[1,2]]'

**Comment by fangq** [comment]
this is now fixed. 

`savejson` encodes 4 types of arrays - numerical arrays, string arrays, cell arrays and struct arrays. Currently, only numerical arrays have explicitly defined rules on serialization of N-dimensional arrays (see my JData specification)

https://github.com/fangq/jdata/blob/master/JData_specification.md#direct-storage-of-n-d-arrays

while other arrays are not clearly defined. The result you saw on encoding cell arrays is a result of this ambiguity. 

I just made the above commit to make two things clear:
1. the serialization of cell arrays now follow the same row-major order as the numerical arrays, and 
2. jsonlab now supports ND cell array while previously only supports up to 2D

please test and let me know if you see any side effect of this fix. I've ran all unit-testing and example scripts, and they seem to work ok.
