### ISSUE TITLE
Fileread issue with non en-US MATLAB

### ISSUE THREAD

**Issue by da1910** [fangq/jsonlab#67]
MATLAB's function fileread does not provide a way to specify file input encoding, which means that different results are obtained in different locales. This is particularly problematic with Asian locales when trying to read strings including emoji.

Suggested fix from Mathworks is to use fopen instead, this allows input encoding to be specified.

**Comment by fangq** [comment]
@da1910, from the help info of fileread, it is supposed to automatically detect the file encodings, see
https://www.mathworks.com/help/matlab/ref/fileread.html

do you have an example where it does not detect the encoding consistent across locales?

**Comment by da1910** [comment]
See response from mathworks support:

```
I am writing in reference to your Technical Support Case #04395812 regarding 'Emoji support in Korean locale'.

After collaborating with my colleagues I found the issue here is that 'fileread' uses a system dependent encoding, which interprets the character differently on different platforms.
To get around this, you can instead call 'fopen'

>> fid = fopen(filename,'r','n','utf-8')

>> data = fread(fid,'*char')';

>> fclose(fid);

This should work, assuming the data is UTF-8 encoded.
Additionally, in MATLAB R2020a, 'fileread' detects the encoding automatically.```

II can provide an example if you need, but I think it will be challenging to write a unit test for this behaviour!

**Comment by fangq** [comment]
sorry for dropping the ball for so long.

there is a `Encoding` flag supported by `loadjson`, it was added back in 2019. if you specify Encoding, loadjson will open the file with `fopen` instead of `fileread`. 

https://github.com/fangq/jsonlab/blob/master/loadjson.m#L87-L88

does this flag work for you?

**Comment by da1910** [comment]
I do not have an easy test for this, but that is the suggested fix, so I'm going to close this as it looks done!
