### ISSUE TITLE
NestArray default value

### ISSUE THREAD

**Issue by wrgrant** [fangq/jsonlab#69]
I just spent a couple hours debugging an issue loading UBJSON created via `savebj()` from Matlab in Node.js using the `@shelacek/ubjson` package.

It turns out I needed to enable `NestArray` in the `savebj()` call.

I think it would make sense to enable `NestArray` automatically if the user has specified `UBJSON` as the output format in order to keep people from dealing with this issue.

From a UX perspective, the note for the `UBJSON` option states it will use the Draft 12 style. I thought this covered me. I didn't realize I also had to search all other options to manually set them to match Draft 12.

You seem to do this already when the user selects `MessagePack` as the output format.

**Comment by fangq** [comment]
you should call `saveubjson.m` instead, see this help info 

https://github.com/fangq/jsonlab/blob/master/saveubjson.m#L20-L27

**Comment by wrgrant** [comment]
Got it. Thanks.
