### ISSUE TITLE
Encoding scalar values into array unnecessarily

### ISSUE THREAD

**Issue by wrgrant** [fangq/jsonlab#70]
Last one (for now) 😉 

I notice that in [this line](https://github.com/fangq/jsonlab/blob/0a393469768575fe07d89f74ee75ced9d8d20c34/savebj.m#L799) you are packing scalar values into an array.
But only for floats. Integers [don't do this](https://github.com/fangq/jsonlab/blob/0a393469768575fe07d89f74ee75ced9d8d20c34/savebj.m#L774).

Is this a bug or is this expected behavior?

With the current behavior, I end up with interesting data results such as this attached image (after pulling into JavaScript). Note, the single integer is placed directly as a scalar, while the single float value is packed into a single element array.

![2020-10-01_17h06_01](https://user-images.githubusercontent.com/3092780/94883342-6c80eb80-0438-11eb-9785-339db6c6782e.png)

I found that changing the float encoding line to:
`txt=D_(mat,varargin{:});`
yielded what I expect to be correct results.

But I'm curious if there is some other design decision that this change would break?

**Comment by fangq** [comment]
sorry, did not pay attention to my notifications until now. 

I agree this is an inconsistency in the code. I believe this was more of a historical reason why it was written this way. 

I made the above commit and it should now output single float value if the `SingletArray` flag is 0 (default). 

let me know if this patch works for you
