### ISSUE TITLE
房老师，您好，我是汽车V2X方向的开发工程师

### ISSUE THREAD

**Issue by a982865151** [fangq/jsonlab#72]
最近利用交通仿真软件和simulink联合，仿真了些场景数据，然后想要把simulink输出的数据先保存到mat文件中，然后转成json格式，输出给汽车控制器测试使用。请问可以寻求您的帮助吗？

**Comment by fangq** [comment]
@a982865151你好，很乐意提供帮助。请问具体的问题是什么？
