### ISSUE TITLE
Change README.txt from Latin-1 to UTF-8?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [fangq/jsonlab#88]
`Fran�ois` could be changed to `François`.

[**jsonlab/README.txt**](https://github.com/fangq/jsonlab/blob/33c5e4b7986da1b5ed5427e9746e0931ada79993/README.txt#564)
Line 564 in 33c5e4b
```
* Fran�ois Glineur: http://www.mathworks.com/matlabcentral/fileexchange/23393
 ```

**Comment by DimitriPapadopoulos** [comment]
Or perhaps remove `README.txt` altogether following 154ef61e3bcb74c98fb4dbe46fc0a375b54d789a?

**Comment by fangq** [comment]
thanks. I removed the file as suggested. I used to keep a wiki-formatted README to update the website (which uses wiki/wikimedia markup language instead of the github markup), but I haven't been updating for a while. so perhaps it is time to retire it.
