### ISSUE TITLE
special characters in strings are not escaped

### ISSUE THREAD

**Issue by nickanthony-dgl** [fangq/jsonlab#89]
If a JSON string contains special characters such as a newline, the special characters should be escaped so as not to interfere with the saved file. For example, this Python code:

```python
import json
json.dumps({"text": "First Line\nSecond Line"})
```
Results in a Python string of:
```
'{"text": "First Line\\nSecond Line"}'
```

which, when saved to a file, will appear in a text editor as:
```
{"text": "First Line\nSecond Line"}
```

This allows successful round-tripping of the JSON data. However, in JSONlab the special character will not be escaped. When opening the resulting file in a text editor it will look like:
```
{"text": "FirstLine
Second Line"}
```

and the data cannot be successfully parsed as JSON

**Comment by fangq** [comment]
can't reproduce this. jsonlab's `savejson` does correctly escape newline character
```
>> loadjson('{"text": "First Line\nSecond Line"}')

ans = 

  struct with fields:

    text: 'First Line↵Second Line'

>> savejson(loadjson('{"text": "First Line\nSecond Line"}'))

ans =

    '{
     	"text":"First Line\nSecond Line"
     }
     '
```

**Comment by fangq** [comment]
@nickanthony-dgl, you can directly save the file using `savejson(..., 'filename', fname);` internally, it has been using binary IO `fwrite()` to avoid double escaping issue like this.
