### ISSUE TITLE
Problem with long JSON keys and special characters

### ISSUE THREAD

**Issue by nickanthony-dgl** [fangq/jsonlab#90]
If a JSON key has special characters than JSONLab substitutes the characters with Hex so that it is still a valid MATLAB variable name. So `Det Input: Offset Angle Y (degrees)` becomes `Det_0x20_Input_0x3A__0x20_Offset_0x20_Angle_0x20_Y_0x20__0x28_degrees_0x29_`

However now the name is too long for MATLAB's 63 character limit on variable names. The name is truncated and the end result is that the JSON data is not correctly round-tripped. Other JSON libraries I have used don't run into this issue because they use the JSON key string as a key to a map rather than trying to use them as variable names.

Is there any way to get JSONLab to use something like a [container.Map](https://www.mathworks.com/help/matlab/ref/containers.map.html) instead of  a struct so that this issue can be bypassed?

**Comment by fangq** [comment]
yes, you should set the `UseMap` option to 1 to avoid this name string limit.

https://github.com/fangq/jsonlab/blob/master/loadjson.m#L46

**Comment by nickanthony-dgl** [comment]
Thanks @fangq , I'm not sure how I manage to miss that when looing through the function documentation.
