### ISSUE TITLE
`null` converted to `[]`

### ISSUE THREAD

**Issue by nickanthony-dgl** [fangq/jsonlab#91]
JSON `null` values are not round-tripped. For example, this `savejson(loadjson('{"myNullValue": null}'))` results in:
```
ans =

    '{
     	"myNullValue":[]
     }
     '
```

The problem appears to be here: https://github.com/fangq/jsonlab/blob/cf573262eb12c1d1dc3668913c1f902e3452f566/loadjson.m#L560

**Comment by fangq** [comment]
matlab does not have a built-in data structure that is equivalent to `null` - the closest is `[]`.

if you run matlab's built-in `jsondecode` function, it also maps `null` to '[]'

```
>> jsondecode('{"a":null}')

ans = 

  struct with fields:

    a: []
```

**Comment by nickanthony-dgl** [comment]
Yes, the problems I was running into with the built-in JSON functions are actually the reason I've started using JSONLab. Wouldn't it be possible to create a custom [class](https://www.mathworks.com/help/matlab/object-oriented-programming.html) to act as json null type?

**Comment by fangq** [comment]
here is my solution, committed as https://github.com/fangq/jsonlab/commit/747c99b5d434ce9f90097ddc0ad98bf1d5d45964

1. define an [optional flag](https://github.com/fangq/jsonlab/blob/cf573262eb12c1d1dc3668913c1f902e3452f566/savejson.m#L144-L163), for example, `EmptyArrayAsNull`, set to 0 by default, but can be enabled in your case
2. test that flag in [this block inside `matdata2json()`](https://github.com/fangq/jsonlab/blob/cf573262eb12c1d1dc3668913c1f902e3452f566/savejson.m#L743-L746), and return `null` if enabled.

this should give you what you want, i.e.
```
>> savejson('', loadjson('{"a":{},"b":[],"c":null}'), 'EmptyArrayAsNull',0, 'Compact', 1)

ans =

    '{"a":[],"b":[],"c":[]}'

>> savejson('', loadjson('{"a":{},"b":[],"c":null}'), 'EmptyArrayAsNull',1, 'Compact', 1)

ans =

    '{"a":null,"b":[],"c":null}'
```
