### ISSUE TITLE
Arrays with one element are converted to scalars

### ISSUE THREAD

**Issue by nickanthony-dgl** [fangq/jsonlab#93]
This can be demonstrated by the failure to roundtrip something as simple as:
```
savejson('', loadjson('{"myArray": [{"mySubItem": 1}]}'))

ans =

    '{
     	"myArray":{
     		"mySubItem":1
     	}
     }
     '
```

**Comment by fangq** [comment]
@nickanthony-dgl, this is by design - jsonlab collapse singlet array. if you want to disable this, you should set option `SingletArray` to 1
```
savejson('', loadjson('{"myArray": [{"mySubItem": 1}]}'), 'SingletArray', 1)
```

the documentation is at https://github.com/fangq/jsonlab/blob/master/savejson.m#L49-L52

**Comment by nickanthony-dgl** [comment]
The `SingleArray` options causes the opposite error to occur:
```
>> savejson('', loadjson('{"myScalarVal": 1}'), 'SingletArray', 1)

ans =

    '{
     	"myScalarVal":[1]
     }
     '
```

Is there a way that works for a JSON structure that may include arrays and scalars?: `'{"myArray": [{"mySubItem": 1}], "myVal": 1}'`
